---
name: terraform-plan

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install aqua
        uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.59.1

      - name: List targets
        id: list-targets
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: list-targets

  plan:
    name: "plan (${{ matrix.target.target }})"
    needs: setup
    if: "join(fromJSON(needs.setup.outputs.targets), '') != ''"
    runs-on: ${{ matrix.target.runs_on }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{ matrix.target.working_directory }}
      TFACTION_JOB_TYPE: ${{ matrix.target.job_type }}
      TFACTION_SKIP_TERRAFORM: "${{ matrix.target.skip_terraform }}"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install aqua
        uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.59.1

      - name: Set up
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: setup
          github_token: ${{ github.token }}

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: terraform-init
          github_token: ${{ github.token }}

      - name: Test
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: test
          github_token: ${{ github.token }}

      - name: Plan
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: terraform-plan
          github_token: ${{ github.token }}
