---
name: terraform-apply

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

env:
  TFACTION_IS_APPLY: "true"

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install aqua
        uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.59.1

      - name: List targets
        id: list-targets
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: list-targets

  apply:
    name: "apply (${{ matrix.target.target }})"
    needs: setup
    if: "join(fromJSON(needs.setup.outputs.targets), '') != ''"
    runs-on: ${{ matrix.target.runs_on }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{ matrix.target.working_directory }}
      TFACTION_JOB_TYPE: ${{ matrix.target.job_type }}
      TFACTION_SKIP_TERRAFORM: "${{ matrix.target.skip_terraform }}"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      actions: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install aqua
        uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.59.1

      - name: Set up
        id: setup
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: setup
          github_token: ${{ github.token }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          service_account: ${{ steps.setup.outputs.gcp_service_account }}
          workload_identity_provider: ${{ steps.setup.outputs.gcp_workload_identity_provider }}

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: terraform-init
          github_token: ${{ github.token }}

      - name: Apply
        uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        with:
          action: terraform-apply
          github_token: ${{ github.token }}
